dataset_params:
  # add
  dataset:
    name: 'hm36'
    path: 'data/hm36'
    train_image_set: 'train_selected'
    test_image_set: 'valid'
    sample_interval: 60    # min random sample gap
    extra_param: ''  # add desciption for cached pkl
  dataiter:
    mean:
    - 0.0
    - 0.0
    - 0.0
    std:
    - 255.0
    - 255.0
    - 255.0
  smpl_pseudo_img:
    use_flag: True
    use_mask: True
    data_path: 'data/surreal_h36m_pose_pseudo'
  use_full_kp: False
  rm_bg: True
  cam_id_list: [0, 1, 2, 3]
  geodesic_pt_list: []
  geodesic_param_list: [2, 1, 3, 20, 0.0]


model_params:
  detector_params:
    name: 'resnet_multi'
    num_kp: 18
    depth_dim: 64
    num_hypo: 3
    neighbor_size: 15

  smpl_disc_params:
    name: 'res_sage_gcn_decouple'
    input_dim: 128
    hidden_dim: 128
    output_dim: 128
    num_node: 18   # assert num_kp == num_node
    disc_sup_dim: 3

    num_layers: 2
    use_self_loop: True
    use_pe: True

  smpl_layer_params:
    model_path: 'data/smpl_models'

  physique_mask_generator_params:
    layers: [32, 64, 128]

  parent_ids: [0, 0, 1, 2, 0, 4, 5, 0, 17, 8, 9, 17, 11, 12, 17, 14, 15, 7]
  child_ids:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17]
  flip_pairs: [[1, 4], [2, 5], [3, 6], [14, 11], [15, 12], [16, 13]]

  line_select_ids: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
  body_width: 3.0

  loss_config:
    recons_loss:
      use_dis_map: False
      weight: 0.02
    
    physique_recons_loss:
      use_dis_map: False
      weight: 0.02

    smpl_pseudo_img_loss:
      weight: 1.0

    symmetry_loss:
      weight:
        bone: 0.1
        kp: 0.1
        kp_2d: 0.0

    smpl_disc_loss:
      weight: 0.5
      update_interval: 1

    smpl_gen_loss:
      weight: 0.5

train_params:
  num_epochs: 15
  batch_size: 32
  epoch_milestones: [40]
  lr_kp_detector: 1.0e-4
  lr_discriminator: 1.0e-4
  checkpoint_freq: 2

  patch_width: 256
  patch_height: 256
  rect_3d_width: 2000
  rect_3d_height: 2000
  aug:
      scale_factor: 0.0
      rot_factor: 0
      color_factor: 0.0
      rot_aug_rate: 0.0
      flip_aug_rate: 0.0
      do_flip_aug: False
  #######
